name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Manual trigger

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.3.0'

    - name: Set up AWS Credentials (if applicable)
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: 'us-west-2'

    - name: Terraform Initialization
      run: terraform init

    - name: Terraform Format Check
      run: terraform fmt -check -diff

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
      if: github.ref == 'refs/heads/main'  # Only run apply on main branch

    - name: Set output value
      run: echo "TF_OUTPUT=$(terraform output -raw my_output)" >> $GITHUB_ENV  # Save output as environment variable
