name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main  # Or any branch you want
  pull_request:
    branches:
      - main  # Or any branch you want
  workflow_dispatch:  # This enables manual triggering
