jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=$(echo ${{ secrets.AWS_keys }} | cut -d';' -f1 | cut -d'=' -f2)" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo ${{ secrets.AWS_keys }} | cut -d';' -f2 | cut -d'=' -f2)" >> $GITHUB_ENV
        env:
          AWS_keys: ${{ secrets.AWS_keys }}
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.3.0'

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color
        if: github.ref == 'refs/heads/main'  # Only run apply on main branch
